"""empty message

Revision ID: 32fe5d857d69
Revises: e52662b661d2
Create Date: 2023-12-14 15:54:35.583738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32fe5d857d69'
down_revision = 'e52662b661d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dvadmin_system_dict', schema=None) as batch_op:
        batch_op.drop_column('code1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dvadmin_system_dict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code1', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True))

    # ### end Alembic commands ###
