"""empty message

Revision ID: 5a3a80ce3044
Revises: 32fe5d857d69
Create Date: 2023-12-14 16:03:17.083281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3a80ce3044'
down_revision = '32fe5d857d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dvadmin_system_dict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code1', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dvadmin_system_dict', schema=None) as batch_op:
        batch_op.drop_column('code1')

    # ### end Alembic commands ###
