"""empty message

Revision ID: 96f055960281
Revises: 5a3a80ce3044
Create Date: 2023-12-14 16:04:05.981888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96f055960281'
down_revision = '5a3a80ce3044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dvadmin_system_dict', schema=None) as batch_op:
        batch_op.drop_column('code1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dvadmin_system_dict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code1', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True))

    # ### end Alembic commands ###
